### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by kbotnen** [EvanPurkhiser/dots#18]
Hi,

Not neccessary an issue with the code, but maybe with the documentation.

When trying to execute the "dots help" or any other dots command I get warning about:

$ dots help
/usr/bin/env: python2.7: No such file or directory

Fixing the python pointer to my actual python version (2.6.6) yields: 

$ dots help
Traceback (most recent call last):
  File "~/.local/bin/dots", line 83, in <module>
    import argparse
ImportError: No module named argparse

So what I can read from this little "test" is that dots is not compatible with python < 2.7?

Maybe the requirements should be stated in the documentation? Or maybe I have misunderstood something and it should be compatible with python2.6 too?

Anyway, seems like a nice tool, Ill try it on some of my other system and see if it works there :) The system I had problem with is RHEL6.5

- Kristian -

**Comment by EvanPurkhiser** [comment]
Kristian - Yes, dots is not supported on python 2.6, unfortunately argparse wasn't introduced until 2.7. I've just added support for Python 3 if that piques your interest at all :-)

I did add a mention of version support to the readme.
