### ISSUE TITLE
python 2.7 support is broken

### ISSUE THREAD

**Issue by countsudoku** [EvanPurkhiser/dots#22]
With the new implemented correct hashing of utf-8 files in commit d25236998aa609d1aa0586ffe2d5208747cc318b  the python 2.7 support gets broken, because the python 2.7 open command doesn't have a encoding argument.

**Comment by EvanPurkhiser** [comment]
Good catch thank you. Will look into this.

**Comment by EvanPurkhiser** [comment]
Should be fixed by f0d4aaa0248a15890d084675eae2e4d5d3c7e5d1
