### ISSUE TITLE
Move config-groups into ~/.config/dots/

### ISSUE THREAD

**Issue by samatjain** [EvanPurkhiser/dots#9]
At the moment, config-groups is in ~/.config/. It's not obvious that this file belongs to dots.

Since #6 will require more configuration be stored, config-groups should be moved into ~/.config/dots/.

**Comment by EvanPurkhiser** [comment]
Moved the `config-groups` file into `INSTALL_DIR/dots` in e623f245ae66c73e18fa13ada4f1c9ccb1d1ddd9.
